// ============================================================
// Mountain Dataset — 25 New England ski mountains
// Snow depth populated at runtime by api.js (Open-Meteo)
// ============================================================

const MOUNTAINS = [
  {
    id: "killington",
    name: "Killington",
    state: "VT",
    lat: 43.6045,
    lng: -72.7787,
    baseElev: 1165,
    peakElev: 4241,
    vertical: 3050,
    runs: 155,
    lifts: 22,
    acres: 1509,
    pass: "ikon",
    weekendPrice: 219,
    weekdayPrice: 149,
    conditionsUrl: "https://www.killington.com/mountain/snow-report",
    live: { snowDepth: null }
  },
  {
    id: "stowe",
    name: "Stowe",
    state: "VT",
    lat: 44.5309,
    lng: -72.7834,
    baseElev: 1559,
    peakElev: 4395,
    vertical: 2360,
    runs: 116,
    lifts: 13,
    acres: 485,
    pass: "epic",
    weekendPrice: 199,
    weekdayPrice: 149,
    conditionsUrl: "https://www.stowe.com/the-mountain/snow-report.aspx",
    live: { snowDepth: null }
  },
  {
    id: "sugarloaf",
    name: "Sugarloaf",
    state: "ME",
    lat: 45.0312,
    lng: -70.3131,
    baseElev: 1400,
    peakElev: 4237,
    vertical: 2820,
    runs: 162,
    lifts: 14,
    acres: 1240,
    pass: "ikon",
    weekendPrice: 189,
    weekdayPrice: 139,
    conditionsUrl: "https://www.sugarloaf.com/the-mountain/snow-conditions",
    live: { snowDepth: null }
  },
  {
    id: "sunday-river",
    name: "Sunday River",
    state: "ME",
    lat: 44.4700,
    lng: -70.8539,
    baseElev: 854,
    peakElev: 3140,
    vertical: 2340,
    runs: 135,
    lifts: 15,
    acres: 870,
    pass: "ikon",
    weekendPrice: 179,
    weekdayPrice: 129,
    conditionsUrl: "https://www.sundayriver.com/the-mountain/snow-report",
    live: { snowDepth: null }
  },
  {
    id: "loon",
    name: "Loon Mountain",
    state: "NH",
    lat: 44.0244,
    lng: -71.6243,
    baseElev: 938,
    peakElev: 3050,
    vertical: 2100,
    runs: 61,
    lifts: 10,
    acres: 370,
    pass: "ikon",
    weekendPrice: 179,
    weekdayPrice: 129,
    conditionsUrl: "https://www.loonmtn.com/the-mountain/conditions-and-weather",
    live: { snowDepth: null }
  },
  {
    id: "cannon",
    name: "Cannon Mountain",
    state: "NH",
    lat: 44.1731,
    lng: -71.6978,
    baseElev: 1923,
    peakElev: 4080,
    vertical: 2180,
    runs: 97,
    lifts: 10,
    acres: 285,
    pass: "independent",
    weekendPrice: 109,
    weekdayPrice: 89,
    conditionsUrl: "https://www.cannonmt.com/conditions",
    live: { snowDepth: null }
  },
  {
    id: "sugarbush",
    name: "Sugarbush",
    state: "VT",
    lat: 44.1337,
    lng: -72.9042,
    baseElev: 1492,
    peakElev: 4135,
    vertical: 2600,
    runs: 111,
    lifts: 16,
    acres: 578,
    pass: "ikon",
    weekendPrice: 169,
    weekdayPrice: 119,
    conditionsUrl: "https://www.sugarbush.com/the-mountain/mountain-report",
    live: { snowDepth: null }
  },
  {
    id: "okemo",
    name: "Okemo",
    state: "VT",
    lat: 43.4046,
    lng: -72.7253,
    baseElev: 1144,
    peakElev: 3343,
    vertical: 2200,
    runs: 121,
    lifts: 20,
    acres: 667,
    pass: "epic",
    weekendPrice: 179,
    weekdayPrice: 129,
    conditionsUrl: "https://www.okemo.com/the-mountain/conditions",
    live: { snowDepth: null }
  },
  {
    id: "mount-snow",
    name: "Mount Snow",
    state: "VT",
    lat: 42.9634,
    lng: -72.9218,
    baseElev: 1900,
    peakElev: 3600,
    vertical: 1700,
    runs: 80,
    lifts: 20,
    acres: 600,
    pass: "epic",
    weekendPrice: 149,
    weekdayPrice: 99,
    conditionsUrl: "https://www.mountsnow.com/mountain/conditions/",
    live: { snowDepth: null }
  },
  {
    id: "stratton",
    name: "Stratton",
    state: "VT",
    lat: 43.1117,
    lng: -72.9087,
    baseElev: 1872,
    peakElev: 3875,
    vertical: 2003,
    runs: 97,
    lifts: 11,
    acres: 670,
    pass: "ikon",
    weekendPrice: 179,
    weekdayPrice: 129,
    conditionsUrl: "https://www.stratton.com/the-mountain/snow-report",
    live: { snowDepth: null }
  },
  {
    id: "jay-peak",
    name: "Jay Peak",
    state: "VT",
    lat: 44.9298,
    lng: -72.5234,
    baseElev: 1815,
    peakElev: 3968,
    vertical: 2153,
    runs: 78,
    lifts: 9,
    acres: 385,
    pass: "independent",
    weekendPrice: 129,
    weekdayPrice: 99,
    conditionsUrl: "https://jaypeakresort.com/mountain/current-conditions",
    live: { snowDepth: null }
  },
  {
    id: "smugglers-notch",
    name: "Smugglers' Notch",
    state: "VT",
    lat: 44.5620,
    lng: -72.7867,
    baseElev: 1020,
    peakElev: 3640,
    vertical: 2610,
    runs: 78,
    lifts: 8,
    acres: 311,
    pass: "independent",
    weekendPrice: 109,
    weekdayPrice: 89,
    conditionsUrl: "https://www.smuggs.com/pages/winter/mtninfo/conditions.cfm",
    live: { snowDepth: null }
  },
  {
    id: "wildcat",
    name: "Wildcat Mountain",
    state: "NH",
    lat: 44.2609,
    lng: -71.2436,
    baseElev: 1902,
    peakElev: 4062,
    vertical: 2112,
    runs: 49,
    lifts: 5,
    acres: 225,
    pass: "epic",
    weekendPrice: 119,
    weekdayPrice: 89,
    conditionsUrl: "https://www.skiwildcat.com/conditions",
    live: { snowDepth: null }
  },
  {
    id: "attitash",
    name: "Attitash",
    state: "NH",
    lat: 44.0784,
    lng: -71.2398,
    baseElev: 600,
    peakElev: 2350,
    vertical: 1750,
    runs: 68,
    lifts: 8,
    acres: 311,
    pass: "epic",
    weekendPrice: 119,
    weekdayPrice: 89,
    conditionsUrl: "https://www.attitash.com/conditions",
    live: { snowDepth: null }
  },
  {
    id: "mount-sunapee",
    name: "Mount Sunapee",
    state: "NH",
    lat: 43.3226,
    lng: -71.9784,
    baseElev: 1510,
    peakElev: 2743,
    vertical: 1510,
    runs: 67,
    lifts: 11,
    acres: 233,
    pass: "epic",
    weekendPrice: 109,
    weekdayPrice: 79,
    conditionsUrl: "https://www.mountsunapee.com/mountain/conditions",
    live: { snowDepth: null }
  },
  {
    id: "waterville-valley",
    name: "Waterville Valley",
    state: "NH",
    lat: 43.9687,
    lng: -71.5115,
    baseElev: 1804,
    peakElev: 4004,
    vertical: 2020,
    runs: 52,
    lifts: 11,
    acres: 255,
    pass: "independent",
    weekendPrice: 119,
    weekdayPrice: 89,
    conditionsUrl: "https://www.waterville.com/mountain-info/mountain-report/",
    live: { snowDepth: null }
  },
  {
    id: "bretton-woods",
    name: "Bretton Woods",
    state: "NH",
    lat: 44.2653,
    lng: -71.4532,
    baseElev: 1700,
    peakElev: 3100,
    vertical: 1500,
    runs: 101,
    lifts: 10,
    acres: 464,
    pass: "independent",
    weekendPrice: 119,
    weekdayPrice: 89,
    conditionsUrl: "https://www.brettonwoods.com/mountain/conditions",
    live: { snowDepth: null }
  },
  {
    id: "crotched",
    name: "Crotched Mountain",
    state: "NH",
    lat: 43.0262,
    lng: -71.9498,
    baseElev: 1008,
    peakElev: 2066,
    vertical: 875,
    runs: 26,
    lifts: 6,
    acres: 80,
    pass: "independent",
    weekendPrice: 79,
    weekdayPrice: 59,
    conditionsUrl: "https://www.crotchedmtn.com/conditions",
    live: { snowDepth: null }
  },
  {
    id: "jiminy-peak",
    name: "Jiminy Peak",
    state: "MA",
    lat: 42.6968,
    lng: -73.2920,
    baseElev: 1150,
    peakElev: 2380,
    vertical: 1150,
    runs: 45,
    lifts: 9,
    acres: 167,
    pass: "ikon",
    weekendPrice: 99,
    weekdayPrice: 79,
    conditionsUrl: "https://www.jiminypeak.com/snow-and-trail-report/",
    live: { snowDepth: null }
  },
  {
    id: "berkshire-east",
    name: "Berkshire East",
    state: "MA",
    lat: 42.5987,
    lng: -72.7745,
    baseElev: 700,
    peakElev: 1880,
    vertical: 1180,
    runs: 45,
    lifts: 5,
    acres: 160,
    pass: "independent",
    weekendPrice: 79,
    weekdayPrice: 59,
    conditionsUrl: "https://berkshireeast.com/conditions/",
    live: { snowDepth: null }
  },
  {
    id: "bolton-valley",
    name: "Bolton Valley",
    state: "VT",
    lat: 44.4048,
    lng: -72.8606,
    baseElev: 1900,
    peakElev: 3150,
    vertical: 1704,
    runs: 71,
    lifts: 6,
    acres: 165,
    pass: "independent",
    weekendPrice: 79,
    weekdayPrice: 59,
    conditionsUrl: "https://www.boltonvalley.com/conditions/",
    live: { snowDepth: null }
  },
  {
    id: "mad-river-glen",
    name: "Mad River Glen",
    state: "VT",
    lat: 44.1835,
    lng: -72.9263,
    baseElev: 1582,
    peakElev: 3637,
    vertical: 2000,
    runs: 53,
    lifts: 4,
    acres: 115,
    pass: "independent",
    weekendPrice: 89,
    weekdayPrice: 69,
    conditionsUrl: "https://www.madriverglen.com/mountain/conditions/",
    live: { snowDepth: null }
  },
  {
    id: "mohawk",
    name: "Mohawk Mountain",
    state: "CT",
    lat: 41.8337,
    lng: -73.2373,
    baseElev: 1000,
    peakElev: 1650,
    vertical: 650,
    runs: 25,
    lifts: 7,
    acres: 112,
    pass: "independent",
    weekendPrice: 59,
    weekdayPrice: 49,
    conditionsUrl: "https://www.mohawkmtn.com/trail-conditions/",
    live: { snowDepth: null }
  },
  {
    id: "ski-sundown",
    name: "Ski Sundown",
    state: "CT",
    lat: 41.9248,
    lng: -72.9826,
    baseElev: 750,
    peakElev: 1450,
    vertical: 700,
    runs: 15,
    lifts: 4,
    acres: 100,
    pass: "independent",
    weekendPrice: 55,
    weekdayPrice: 45,
    conditionsUrl: "https://www.skisundown.com/trail-report/",
    live: { snowDepth: null }
  },
  {
    id: "yawgoo",
    name: "Yawgoo Valley",
    state: "RI",
    lat: 41.5265,
    lng: -71.6254,
    baseElev: 150,
    peakElev: 395,
    vertical: 245,
    runs: 18,
    lifts: 3,
    acres: 27,
    pass: "independent",
    weekendPrice: 45,
    weekdayPrice: 35,
    conditionsUrl: "https://www.yawgoo.com/conditions/",
    live: { snowDepth: null }
  }
];

// Derived ranges for slider init
const DATA_RANGES = {
  runs:        { min: 0, max: Math.max(...MOUNTAINS.map(m => m.runs)) },
  lifts:       { min: 0, max: Math.max(...MOUNTAINS.map(m => m.lifts)) },
  peakElev:    { min: Math.min(...MOUNTAINS.map(m => m.peakElev)), max: Math.max(...MOUNTAINS.map(m => m.peakElev)) },
  vertical:    { min: 0, max: Math.max(...MOUNTAINS.map(m => m.vertical)) },
  acres:       { min: 0, max: Math.max(...MOUNTAINS.map(m => m.acres)) },
  weekendPrice:{ min: Math.min(...MOUNTAINS.map(m => m.weekendPrice)), max: Math.max(...MOUNTAINS.map(m => m.weekendPrice)) },
  weekdayPrice:{ min: Math.min(...MOUNTAINS.map(m => m.weekdayPrice)), max: Math.max(...MOUNTAINS.map(m => m.weekdayPrice)) },
};
